name: Release version (Git only)

on:
  pull_request:
    types:
      - closed
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: npm install

      - name: Generate Git tag and changelog
        run: |
          npm run tag:generate
          git push --follow-tags origin main

      - name: Build package
        run: npm run release

      - name: Trigger badge update (optional)
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: 'generate-coverall-report'
