name: Release version and NPM publish manually

on:
  pull_request:
    types:
      - closed
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install Dependencies
        run: npm ci

      # ✅ Build before tagging
      - name: Build project
        run: npm run release

      - name: Create npm package (.tgz)
        run: npm pack

      # ✅ Generate tag and changelog after build
      - name: Generate Git tag and changelog
        run: |
          npm run tag:generate
          git push --follow-tags origin main

      - name: Get latest tag
        id: get_tag
        run: |
          echo "tag_name=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      # ✅ Upload .tgz to GitHub Release
      - name: Upload .tgz to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          files: ts-query-builder-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger badge update (optional)
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: 'generate-coverall-report'
