name: Release version and GitHub Upload

on:
  pull_request:
    types:
      - closed
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install Dependencies
        run: npm install

      - name: Generate Git Tag
        run: |
          npm run tag:generate
          git push --follow-tags origin main

      - name: Build App
        run: npm run release

      - name: Zip dist folder
        run: zip -r dist.zip dist

      - name: Create GitHub Release and Upload dist.zip
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Badge Generation
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: 'generate-coverall-report'
